import { createHash } from 'node:crypto';
import { access, cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outRoot = resolve(root, 'vendor', 'tesseract-7.0.0');

const required = [
  ['node_modules/tesseract.js/dist/tesseract.min.js', 'tesseract.min.js'],
  ['node_modules/tesseract.js/dist/worker.min.js', 'worker.min.js'],
  ['node_modules/@tesseract.js-data/eng/4.0.0_best_int/eng.traineddata.gz', 'lang/eng.traineddata.gz'],
  ['node_modules/tesseract.js-core/tesseract-core-lstm.wasm.js', 'core/tesseract-core-lstm.wasm.js'],
  ['node_modules/tesseract.js-core/tesseract-core-lstm.wasm', 'core/tesseract-core-lstm.wasm'],
  ['node_modules/tesseract.js-core/tesseract-core-simd-lstm.wasm.js', 'core/tesseract-core-simd-lstm.wasm.js'],
  ['node_modules/tesseract.js-core/tesseract-core-simd-lstm.wasm', 'core/tesseract-core-simd-lstm.wasm'],
  ['node_modules/tesseract.js-core/tesseract-core-relaxedsimd-lstm.wasm.js', 'core/tesseract-core-relaxedsimd-lstm.wasm.js'],
  ['node_modules/tesseract.js-core/tesseract-core-relaxedsimd-lstm.wasm', 'core/tesseract-core-relaxedsimd-lstm.wasm']
];

const optionalLicenses = [
  ['node_modules/tesseract.js/LICENSE.md', 'licenses/tesseract.js-LICENSE.md'],
  ['node_modules/tesseract.js-core/LICENSE', 'licenses/tesseract.js-core-LICENSE'],
  ['node_modules/@tesseract.js-data/eng/LICENSE', 'licenses/eng-traineddata-LICENSE'],
  ['node_modules/@tesseract.js-data/eng/README.md', 'licenses/eng-traineddata-README.md']
];

async function exists(path) {
  try { await access(path); return true; } catch { return false; }
}

async function copyOne(sourceRel, destRel, requiredFile = true) {
  const source = resolve(root, sourceRel);
  const destination = resolve(outRoot, destRel);
  if (!(await exists(source))) {
    if (requiredFile) throw new Error(`Missing required dependency file: ${sourceRel}`);
    return false;
  }
  await mkdir(dirname(destination), { recursive: true });
  await cp(source, destination, { force: true });
  return true;
}

async function sha256(path) {
  const bytes = await readFile(path);
  return createHash('sha256').update(bytes).digest('hex');
}

await rm(outRoot, { recursive: true, force: true });
await mkdir(outRoot, { recursive: true });

for (const [source, destination] of required) await copyOne(source, destination, true);
for (const [source, destination] of optionalLicenses) await copyOne(source, destination, false);

const versions = [
  'Trade Vault local OCR vendor bundle',
  'tesseract.js=7.0.0',
  'tesseract.js-core=7.0.0',
  '@tesseract.js-data/eng=1.0.0',
  '',
  'Runtime policy: local files only; no OCR CDN is configured by Trade Vault.',
  'Generated by tools/vendor-ocr.mjs from exact versions pinned in package.json.',
  ''
].join('\n');
await writeFile(resolve(outRoot, 'VERSIONS.txt'), versions, 'utf8');

const hashTargets = [...required.map(([, dest]) => dest), 'VERSIONS.txt'];
const hashLines = [];
for (const relative of hashTargets) {
  const digest = await sha256(resolve(outRoot, relative));
  hashLines.push(`${digest}  ${relative}`);
}
await writeFile(resolve(outRoot, 'SHA256SUMS.txt'), `${hashLines.join('\n')}\n`, 'utf8');

console.log(`Vendored ${required.length} required OCR files into ${outRoot}`);
console.log('Generated SHA256SUMS.txt. Deploy the vendor/tesseract-7.0.0 directory with the app.');
