'use strict';

const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const inputs = [
  'src/game-engine.js',
  'src/player-data.js',
  'src/app.js'
];
const output = path.join(root, 'src/picklepulse-core.js');
const banner = `/* PicklePulse browser core. Generated by npm run build:core. */\n`;
const body = inputs.map((file) => fs.readFileSync(path.join(root, file), 'utf8').trim()).join('\n\n');
fs.writeFileSync(output, `${banner}${body}\n`);
console.log(`Built ${path.relative(root, output)} from ${inputs.length} source files.`);
